---
- name: Configure IPv4 addresses on underlay interfaces
  ansible.netcommon.netconf_config:
    target: candidate
    content: |
      <config>
        <interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg">
          <interface-configuration>
            <active>act</active>
            <interface-name>{{ item.name }}</interface-name>
            <ipv4-network xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-io-cfg">
              <addresses>
                <primary>
                  <address>{{ item.address.split('/')[0] }}</address>
                  <netmask>255.255.255.254</netmask>
                </primary>
              </addresses>
            </ipv4-network>
          </interface-configuration>
        </interface-configurations>
      </config>
    commit: true
  loop: "{{ underlay_interfaces }}"