hostname: ic-node-3

underlay_interfaces:
  - name: GigabitEthernet0/0/0/0
    address: 10.0.0.1/31
  - name: Gi0/0/0/1
    address: 10.0.0.5/31

bgp_rid:
  asn: 65000
  router_id: 100.64.60.3

isis:
  process: UNDERLAY
  net: 49.0001.0000.0000.0003.00