hostname: ic-node-4

underlay_interfaces:
  - name: GigabitEthernet0/0/0/0
    address: 10.0.0.3/31
  - name: GigabitEthernet0/0/0/1
    address: 10.0.0.7/31

bgp_rid:
  asn: 65000
  router_id: 100.64.60.4

isis:
  process: UNDERLAY
  net: 49.0001.0000.0000.0004.00