---
# main playbook
- hosts: ic-core
  gather_facts: false
  roles:
    - role: netconf_yang
- hosts: all
  gather_facts: false
  tasks:
    - name: Save Running-Config to Startup-Config
      cisco.nxos.nxos_config:
        save_when: always