name: Terraform Apply Prod Environment

on:
  workflow_run:
    workflows:
      - Terraform Apply Test Environment
    types:
      - completed

jobs:
  terraform:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, linux, x64]
    environment: Prod

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Debug Terraform folder
        run: |
          pwd
          ls -la
          echo "----- main.tf -----"
          cat main.tf

      - name: Terraform init
        run: |
          terraform init -upgrade -reconfigure \
            -backend-config="path=/opt/terraform-statefile/iosxr-mpls-prod/terraform.tfstate"

      - name: Terraform validate
        run: terraform validate

      - name: Debug environment variables
        run: |
          echo "IC_NODE_1_OOBM_IP='${{ vars.IC_NODE_1_OOB_IP }}'"
          echo "IC_NODE_2_OOBM_IP='${{ vars.IC_NODE_2_OOB_IP }}'"
          echo "IC_NODE_3_OOBM_IP='${{ vars.IC_NODE_3_OOB_IP }}'"
          echo "IC_NODE_4_OOBM_IP='${{ vars.IC_NODE_4_OOB_IP }}'"

      - name: Rendering Net-as-Code config
        env:
          IC_NODE_1_OOBM_IP: ${{ vars.IC_NODE_1_OOB_IP }}
          IC_NODE_2_OOBM_IP: ${{ vars.IC_NODE_2_OOB_IP }}
          IC_NODE_3_OOBM_IP: ${{ vars.IC_NODE_3_OOB_IP }}
          IC_NODE_4_OOBM_IP: ${{ vars.IC_NODE_4_OOB_IP }}
        run: |
          envsubst < data/global_config_vars.nac.yml > config/global_config_vars.rendered.nac.yml
          envsubst < data/group_config_vars.nac.yml > config/group_config_vars.rendered.nac.yml
          envsubst < data/device_config_vars.nac.yml > config/device_config_vars.rendered.nac.yml
          echo "----- rendered NAC config -----"
          cat config/global_config_vars.rendered.nac.yml
          cat config/group_config_vars.rendered.nac.yml
          cat config/device_config_vars.rendered.nac.yml

      - name: Terraform plan
        env:
          IOSXR_USERNAME: ${{ secrets.IOSXR_USERNAME }}
          IOSXR_PASSWORD: ${{ secrets.IOSXR_PASSWORD }}
        run: terraform plan -out=tfplan

      - name: Terraform apply
        env:
          IOSXR_USERNAME: ${{ secrets.IOSXR_USERNAME }}
          IOSXR_PASSWORD: ${{ secrets.IOSXR_PASSWORD }}
        run: terraform apply -auto-approve tfplan