name: Terraform Apply Test Environment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: [self-hosted, linux, x64]
    environment: Test

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Terraform folder
        run: |
          pwd
          ls -la
          echo "----- main.tf -----"
          cat main.tf
          echo "----- cleanup -----"
          rm -rf .terraform
          rm -f .terraform.lock.hcl

      - name: Terraform init
        run: terraform init -upgrade

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        env:
          TF_VAR_username: ${{ secrets.IOSXR_USERNAME }}
          TF_VAR_password: ${{ secrets.IOSXR_PASSWORD }}
        run: terraform plan -out=tfplan

      - name: Terraform apply
        env:
          TF_VAR_username: ${{ secrets.IOSXR_USERNAME }}
          TF_VAR_password: ${{ secrets.IOSXR_PASSWORD }}
        run: terraform apply -auto-approve tfplan